config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists
  root "todos#index"
  resources :todos
  get "sessions/login" => 'sessions#login'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
    validates :description, presence: true
    enum status: [:completed, :incomplete]
    belongs_to :user
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
    has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery except: :receive_guest

    def current_or_guest_user
        if current_user
            if session[:guest_user_id] && session[:guest_user_id] != current_user.id
                logging_in
                guest_user(with_retry = false).reload.try(:destroy)
                session[:guest_user_id] = nil
            end
            current_user
        else
            guest_user
        end
    end

    def guest_user(with_retry = true)
        @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)
    rescue ActiveRecord::RecordNotFound
        session[:guest_user_id] = nil
        guest_user if with_retry
    end

    private

    def logging_in
    end

    def create_guest_user
        password = SecureRandom.hex(6)
        u = User.create(email: "guest_#{Time.now.to_i}#{rand(100)}@suyesh.com", password: password, password_confirmation: password)
        u.save!(validate: false)
        session[:guest_user_id] = u.id
        # Sample Task for the guest user
        u.todos.create(description: 'Hover to delete this sample task.', priority: 'High')
        u
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def login
        @user = User.find(params[:id])
        session[:guest_user_id] = @user.id
        redirect_to root_path
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
    before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

    # GET /todo_lists
    # GET /todo_lists.json
    def index
        @todo_lists = TodoList.all
    end

    # GET /todo_lists/1
    # GET /todo_lists/1.json
    def show
    end

    # GET /todo_lists/new
    def new
        @todo_list = TodoList.new
    end

    # GET /todo_lists/1/edit
    def edit
    end

    # POST /todo_lists
    # POST /todo_lists.json
    def create
        @todo_list = TodoList.new(todo_list_params)

        respond_to do |format|
            if @todo_list.save
                format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
                format.json { render :show, status: :created, location: @todo_list }
            else
                format.html { render :new }
                format.json { render json: @todo_list.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /todo_lists/1
    # PATCH/PUT /todo_lists/1.json
    def update
        respond_to do |format|
            if @todo_list.update(todo_list_params)
                format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
                format.json { render :show, status: :ok, location: @todo_list }
            else
                format.html { render :edit }
                format.json { render json: @todo_list.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /todo_lists/1
    # DELETE /todo_lists/1.json
    def destroy
        @todo_list.destroy
        respond_to do |format|
            format.html { redirect_to todo_lists_url, notice: 'Todo list was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
        @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
        params.require(:todo_list).permit(:description)
    end
end

app/controllers/todos_controller.rb
require 'rqrcode_png'
class TodosController < ApplicationController
    helper_method :current_or_guest_user
    def index
        @todos = guest_user.todos.all
        @todo = guest_user.todos.new
        @qr = RQRCode::QRCode.new('https://montodo.herokuapp.com' + sessions_login_path.to_s + "?id=#{guest_user.id}").to_img.resize(100, 100).to_data_url
    end

    def new
        @todo = guest_user.todos.new
    end

    def create
        @todo = guest_user.todos.create(todo_params)
        @todos = guest_user.todos.all
        respond_to do |format|
            format.html { redirect_to root_path }
            format.js do
                if @todo.save
                    render 'success'
                else
                    flash.now[:alert] = 'Task length cannot exceed 25 characters'
                    render 'new'
               end
            end
        end
    end

    def edit
        @todo = Todo.find(params[:id])
        @todos = guest_user.todos.all
        respond_to do |format|
            format.js
        end
    end

    def update
        @todo = Todo.find(params[:id])
        @todos = guest_user.todos.all
        if @todo.incomplete?
            @todo.complete!
        else
            @todo.incomplete!
        end
        respond_to do |format|
            format.js do
                flash[:alert] = 'Task Updated completed'
                render 'del_success'
            end
        end
    end

    def destroy
        @todo = guest_user.todos.find(params[:id])
        @todo.destroy
        @todos = guest_user.todos.all
        respond_to do |format|
            format.js do
                flash.now[:alert] = 'Task Succesfully completed'
                render 'del_success'
            end
        end
    end

    private

    def todo_params
        params.require(:todo).permit(:description, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
  def priorities
    %w(High Medium Low )
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Montodo</title>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="//cdnjs.cloudflare.com/ajax/libs/animate.css/3.1.1/animate.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <%= csrf_meta_tags %>
    </head>
    <body>
        <div class="container-fluid">
            <div class="logo">
                <%= image_tag("https://s3.amazonaws.com/cdn.shared/todo/ModoTODO.png", :alt => "kewl logo", class: "img-responsive center-block") %>
            </div>

            <%= yield %>
        </div>

    </body>
</html>

app/views/todo_lists/_form.html.erb
<%= simple_form_for(@todo_list) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
    <%= f.input :description %>
</div>

<div class="form-actions">
    <%= f.button :submit %>
</div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %>
|
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Todo Lists</h1>

<table>
    <thead>
        <tr>
            <th>Description</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @todo_lists.each do |todo_list| %>
        <tr>
            <td><%= todo_list.description %></td>
            <td><%= link_to 'Show', todo_list %></td>
            <td><%= link_to 'Edit', edit_todo_list_path(todo_list) %></td>
            <td><%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Description:</strong>
    <%= @todo_list.description %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %>
|
<%= link_to 'Back', todo_lists_path %>

app/views/todos/_alert.html.erb
<% flash.each do |key, message| %>
<div class="alert alert-<%= key %>">
    <%= message %>
</div>
<%end%>

app/views/todos/_todos_tasks.html.erb
<ul>
    <% @todos.each do |todo| %>
    <%= link_to todo_path(todo), method: :delete, remote: true do %>
    <li class="todo-li">
        <div class="fa fa-check"></div>
    </a><%= todo.description %>
    <div class="pull-right">
        <% if todo.priority == "High" %>
        <span class="label label-danger">
            <i class="fa fa-tasks"></i>
        </span>
        <%elsif todo.priority == "Medium"%>
        <span class="label label-primary">
            <i class="fa fa-tasks"></i>
        </span>
        <%else%>
        <span class="label label-warning">
            <i class="fa fa-tasks"></i>
        </span>
        <%end%>
    </div>

</li>
<%end%>
<% end %>
</ul>

app/views/todos/create.js.erb
var html = "<li><%= @todo.description %><br><strong>priority: </strong> <%= @todo.priority %><br><%= escape_javascript link_to 'done', todo_path(@todo), method: 'delete' %></li>";
$('ul').append(html);

app/views/todos/del_success.js.erb
$('ul').html("<%= escape_javascript(render partial: 'todos_tasks') %>");

app/views/todos/destroy.js.erb
$("li#<%= @todo.id %>").append("<s>@todo.description/s>");

app/views/todos/edit.js.erb
$('ul').html("<%= escape_javascript(render partial: 'todos_tasks') %>");

app/views/todos/index.html.erb
<div class="list animated tada">
    <h1>
        To-DO list<a class="add" href="#" data-toggle="modal" data-target="#task-add">
            <div class="fa fa-plus"></div>
        </a>
    </h1>
    <%= render "todos_tasks" %>
    <button class="btn btn-primary center-block qr" data-toggle="modal" data-target="#QR">
        <small>Click here to sync Tasks with multiple devices</small>
    </button>

</div>

<div class="modal modal-message modal-success fade" tabindex="-1" role="dialog" id="task-add">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Add Task</h4>

            </div>
            <div class="modal-body">
                <%= simple_form_for @todo, remote: true do |f| %>
                <%= f.input :description, :label => "Task", placeholder: "Get Milk and Bread."%>
                <%= f.input :priority, :label => "Priority level", :collection => priorities, :selected => "High"%>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <%= f.button :submit, "Add Task" , class: "btn btn-primary"%>
            </div>
            <%end%>
        </div>
        <!-- /.modal-content -->

    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal modal-message modal-success fade" tabindex="-1" role="dialog" id="QR">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Scan this Qr to Sync your tasks with multiple devices</h4>
            </div>
            <div class="modal-body">
                <%= image_tag @qr %>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
        <!-- /.modal-content -->

    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/todos/success.js.erb
$('ul').html("<%= escape_javascript(render partial: 'todos_tasks') %>");
$('#task-add').modal('toggle');